### ISSUE TITLE
Get accessibility statistics for (LSOA?) geographic zones and upload as release

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/acton#12]

**Comment by Robinlovelace** [comment]
Challenge: get the accessibility data for the site according to data linked to here https://www.gov.uk/government/collections/journey-time-statistics

**Comment by mem48** [comment]
I have some of this pre formatted in creds repos

**Comment by Robinlovelace** [comment]
Please share... best I've got is in here: https://github.com/ITSLeeds/SSPA/blob/master/accessability.Rmd

**Comment by mem48** [comment]
https://github.com/creds2/Excess-Data-Exploration/blob/master/Rscripts/prep_data/prep_accessability.R

**Comment by Robinlovelace** [comment]
Thanks @mem48, good starting point.
