### ISSUE TITLE
Automatically creating, tagging and re-saving OSM data objects (especially new cycleways)

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/acton#25]
Discussed with @mem48 this morning. I think the best offline approach is JOSM, which has a good CLI that can do auto-tagging and re-saving as .osm files. See here: https://wiki.openstreetmap.org/wiki/JOSM/Plugins/CommandLine

Sound like a reasonable approach to you @mvl22 in the absence of an iD instance connected to a local DB (overkill at this stage)?

**Comment by mvl22** [comment]
Yes, this is what I said earlier in another ticket:

https://github.com/cyipt/acton/issues/4#issuecomment-571691291

**Comment by Robinlovelace** [comment]
> Yes, this is what I said earlier in another ticket:

Not quite, you didn't include a link to a way of automated tagging or saving back out to the .osm file format. But  https://wiki.openstreetmap.org/wiki/JOSM/Plugins/CommandLine strengthens your argument for using JOSM.

**Comment by mem48** [comment]
I haven't done a comparison of JOSM in the command line vs osmfilter https://wiki.openstreetmap.org/wiki/Osmfilter, but osmfilter does not require java to be installed (so less dependancies) and I have a basic R package supporting it at https://github.com/ITSLeeds/OSMtools

**Comment by Robinlovelace** [comment]
Can `osmfilter` change tags @mem48 ? Very interested if so...

**Comment by mem48** [comment]
Yes

**Comment by Robinlovelace** [comment]
:+1:

**Comment by Robinlovelace** [comment]
> Yes

Do you have a reprex?

**Comment by mem48** [comment]
This is all I written so far https://github.com/ITSLeeds/OSMtools/blob/master/vignettes/osmtools.Rmd
