### ISSUE TITLE
Describe how quietness is measured in CycleStreets?

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/acton#47]
Heads-up @si-the-pie this is the relevant section of the report:

https://github.com/cyipt/acton/blob/master/vignettes/acton.Rmd#L108

Can you write some in there?

**Comment by Robinlovelace** [comment]
The fastest route only considers time, the quietest service.

**Comment by si-the-pie** [comment]
I've added a summary of what I said in the call earlier today to #9 and I'll next add a much shorter version to the vignettes list.

**Comment by si-the-pie** [comment]
I've added to the vignettes at: https://github.com/cyipt/acton/blob/master/vignettes/acton.Rmd#L122

I had to change it quite a lot from my more technical summary - hope that it fits in OK.

**Comment by Robinlovelace** [comment]
This is really great work @si-the-pie, many thanks. Please close this issue when you're happy with the marked-up online version here: https://cyipt.github.io/acton/articles/acton.html#route-data

Could you add some quantitative examples to that text, e.g. "a quietness score of 50% will correspond to a weighting for the segment of 2 times its length".

Also is it worth linking to a future-proof and up-to-date description of quietness on your site?

Otherwise, it's looking good!
