### ISSUE TITLE
Make the dev api default

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/acton#51]
Heads-up @aspeakman

**Comment by mvl22** [comment]
I don't think this is right - the dev is only temporarily the server with the data, but the published package ought to assume the long-term default of using www . So for now I would revert this, but make calling code use dev.

**Comment by Robinlovelace** [comment]
It's a one liner to revert. Will the functionality in the dev version eventually go into the www version? If so we should switch back to the stable version when the functionality has been added, so if there's an ETA on that let us know.

**Comment by mvl22** [comment]
Will do. Yes, Andrew is planning to put the dev changes into www - the data is currently being generated as mentioned on the call.
