### ISSUE TITLE
Add support for dev version of api

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/acton#52]
Enabling us to get queries such as: https://dev.planit.org.uk/api/applics/geojson?limit=250&pg_sz=250&bbox=-1.599425%2C53.768004%2C-1.477340%2C53.838354&app_state=Undecided&app_type=Full%2COutline&app_size=Large

Heads-up @mvl22 (we got this via streetfocus) and @aspeakman - any other search terms we can add to make this zoom-in on the Climate Innovation District and Allerton Bywater applications?

**Comment by aspeakman** [comment]
Do you mean in terms of setting the bbox more precisely?  If so you can use the Planit Perimeter page

See
https://dev.planit.org.uk/perimeter/-1.373595,53.738874,-1.342714,53.750244/
and
https://dev.planit.org.uk/perimeter/-1.530522,53.786632,-1.519457,53.791044/

Press the Change button, adjust the boundary, then press the 'Show data' button and copy the bbox parameter from the resulting data page

**Comment by Robinlovelace** [comment]
> Do you mean in terms of setting the bbox more precisely? If so you can use the Planit Perimeter page

No I meant which other API arguments. I guess size=large will be one of the queries that reduces the 
size of the result while keeping the applications we're interested in.

In hindsight 'zooming in' wasn't the most appropriate way of framing it.

**Comment by aspeakman** [comment]
Here is my current list of what is available:

app_size -> Size of the proposed development

- Large - Major, large scale developments
- Medium - Other applications involving multiple dwellings
- Small - All others

app_state -> Decision status for the application

- Undecided - The application is currently active, no decision has been made
- Permitted - The application was approved
- Conditions - The application was approved, but conditions were imposed
- Rejected - The application was refused
- Withdrawn - The application was withdrawn before a decision was taken
- Referred - The application was referred to government or to another authority
- Unresolved - The application is no longer active but no decision was made eg split decision
- Other - Status not known

app_type -> Type of the application

- Full - Full and householder planning applications
- Outline - Proposals prior to a full application, including assessments, scoping opinions, outline applications etc
- Amendment - Amendments, alterations or conditions arising from existing or previous applications
- Heritage - Conservation issues and listed buildings
- Trees - Tree and hedge works
- Advertising - Advertising and signs
- Telecoms-  Telecommunications including phone masts
- Other - All other types eg agricultural, electrical

**Comment by Robinlovelace** [comment]
Thanks @aspeakman see #48 for issues with `app_size` seemingly.

**Comment by Robinlovelace** [comment]
Closing as these query args are now in the R function `get_planit_data()`:

app_size -> Size of the proposed development

app_state -> Decision status for the application

app_type -> Type of the application

**Comment by mvl22** [comment]
Great, looks good. Nice.

https://github.com/cyipt/acton/blob/master/R/planit.R#L91-L93
